#!/usr/bin/python3
#
# Print song lyrics from https://genius.com/
#
# Usage (Linux):
#   alias xclip="xclip -selection c"
#   ./lyrics [url] | xclip
#
# Usage (MacOS):
#   ./lyrics [url] | pbcopy
#

from bs4 import BeautifulSoup
import sys
import requests

if __name__ == '__main__':
    url = sys.argv[1]
    r = requests.get(url)
    html = r.text
    soup = BeautifulSoup(html, 'html.parser')
    for e in soup.findAll('br'):
        e.extract()
    lyrics = str(soup.find('p'))[3:-4]
    for line in lyrics.split('\n'):
        print(f'"{line}",')
